[theme]
primaryColor = "#008A71"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#332F22"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
